
services:
  # Servicio 1: Nuestro motor de base de datos PostgreSQL
  app:
    build: .
    command: python run.py
    volumes:
      - .:/app  # Sincroniza tu código (punto actual con /app en el contenedor)
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://camiones:SLN3@db:5432/mydb
    depends_on:
      - db
    ports:
      - "5000:5000"
  
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: camiones
      POSTGRES_PASSWORD: SLN3
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    

  # Servicio 2: Nuestra interfaz visual pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
       - pgdata:/var/lib/postgresql/data

# Declaración de volúmenes para la persistencia de datos
volumes: 
  pgdata:
