"""Creacion vehiculos rutas viajes

Revision ID: 2d579c784a37
Revises: 9894d6878205
Create Date: 2026-04-22 09:39:13.667291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d579c784a37'
down_revision = '9894d6878205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('cif_nif', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif_nif')
    )
    op.create_table('conductores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('carnet_conducir', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=100), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=True),
    sa.Column('tiempo_estimado_horas', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('capacidad_toneladas', sa.Float(), nullable=False),
    sa.Column('tipo_grano', sa.String(length=50), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patente')
    )
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_salida', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('conductor_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductores.id'], ),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('camiones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camiones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patente', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('capacidad_toneladas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tipo_grano', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('disponible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('camiones_pkey')),
    sa.UniqueConstraint('patente', name=op.f('camiones_patente_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('viajes')
    op.drop_table('vehiculos')
    op.drop_table('usuarios')
    op.drop_table('rutas')
    op.drop_table('conductores')
    op.drop_table('clientes')
    # ### end Alembic commands ###
