"""Crear tabla camiones

Revision ID: 9894d6878205
Revises: 
Create Date: 2026-04-21 11:48:03.334383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9894d6878205'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('capacidad_toneladas', sa.Float(), nullable=False),
    sa.Column('tipo_grano', sa.String(length=50), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camiones')
    # ### end Alembic commands ###
